
function HDL_Sys_Gen_config(this_block)

  % Revision History:
  %
  %   25-Apr-2022  (17:06 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     D:\Code\Simulink\HDL_Sys_Gen.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('HDL_Sys_Gen');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('m');
  this_block.addSimulinkInport('c');
  this_block.addSimulinkInport('m_clk');

  this_block.addSimulinkOutport('y');

  y_port = this_block.port('y');
  y_port.setType('UFix_7_0');

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('m').width ~= 3);
      this_block.setError('Input data type for port "m" must have width=3.');
    end

    if (this_block.port('c').width ~= 3);
      this_block.setError('Input data type for port "c" must have width=3.');
    end

    if (this_block.port('m_clk').width ~= 1);
      this_block.setError('Input data type for port "m_clk" must have width=1.');
    end

    this_block.port('m_clk').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('HDL_Sys_Gen.vhd');

return;


